### ISSUE TITLE
NoClassDefFoundError app/revanced/patcher/fingerprint/method/impl/MethodFingerprint

### ISSUE THREAD

**Issue by mosin** [nikhilbadyal/docker-py-revanced#410]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

all youtube, reddit

### Error log or link to the logs if using Github Action

Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/fingerprint/method/impl/MethodFingerprint
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at app.revanced.patcher.PatchBundleLoader$1.invoke(PatchBundleLoader.kt:46)
        at app.revanced.patcher.PatchBundleLoader$1.invoke(PatchBundleLoader.kt:45)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.collections.CollectionsKt__MutableCollectionsKt.addAll(MutableCollections.kt:129)
        at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt:54)
        at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt)
        at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt:33)
        at app.revanced.patcher.PatchBundleLoader$Jar.<init>(PatchBundleLoader.kt:94)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:209)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.fingerprint.method.impl.MethodFingerprint
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 35 more

### ENVS

```Dotenv
GLOBAL_CLI_DL=https://github.com/revanced/revanced-cli
 GLOBAL_PATCHES_DL=https://github.com/revanced/revanced-patches
 GLOBAL_PATCHES_JSON_DL=https://github.com/revanced/revanced-patches
 GLOBAL_INTEGRATIONS_DL=https://github.com/revanced/revanced-integrations
#Reddit
 REDDIT_CLI_DL=https://github.com/inotia00/revanced-cli
 REDDIT_PATCHES_DL=https://github.com/YT-Advanced/ReX-patches
 REDDIT_PATCHES_JSON_DL=https://github.com/YT-Advanced/ReX-patches
 REDDIT_INTEGRATIONS_DL=https://github.com/YT-Advanced/ReX-integrations
```

### Additional info

Happens when trying to patch any files.

**Comment by nikhilbadyal** [comment]
Not a builder issue and this isn't the proper place to submit revanced issues. Closing [issue](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)
