### ISSUE TITLE
auto release fails every hour

### ISSUE THREAD

**Issue by FallenLeave91** [nikhilbadyal/docker-py-revanced#525]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

Auto Build & Release

### Error log or link to the logs if using Github Action

From the Should build? task:

0s
Run should_build=$(python check_resource_updates.py)
2024-05-26 14:11:09.375 | INFO     | __main__:check_if_build_is_required:19 - Checking youtube
Traceback (most recent call last):
  File "/home/runner/work/docker-py-revanced/docker-py-revanced/check_resource_updates.py", line 57, in <module>
    check_if_build_is_required()
  File "/home/runner/work/docker-py-revanced/docker-py-revanced/check_resource_updates.py", line 21, in check_if_build_is_required
    old_integration_version = GitHubManager(env).get_last_version(app_obj, integration_version_key)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/docker-py-revanced/docker-py-revanced/src/manager/github.py", line 32, in get_last_version
    with urllib.request.urlopen(self.update_file_url) as url:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Error: Process completed with exit code 1.

### ENVS

```Dotenv
PATCH_APPS=youtube
YOUTUBE_VERSION=19.11.43
EXCLUDE_PATCH_YOUTUBE=always-autorepeat,comments,hide-cast-button
ARCHS_TO_BUILD=arm64-v8a
```

### Additional info

Seems to be same/related to #510. Hope i can provide more info ;)

**Comment by IMXEren** [comment]
It failed to fetch last version details with status code `HTTP Error 404: Not Found`. Seems like status code result other than `200` (try and except block would also suffice) should `return "0"` as well. Just to clarify, this is different to #510 (`undefined issue`).

Try another run and report.

**Comment by FallenLeave91** [comment]
I guess i found the issue. The PERSONAL_ACCESS_TOKEN Var in the Repo Secrets was called PAT. Maybe it was changed and i didn´t notice. I created the new secret under PERSONAL_ACCESS_TOKEN like it´s said in the docs. Got no more errors since then.
