### ISSUE TITLE
Facebook fails to build

### ISSUE THREAD

**Issue by DTM450** [nikhilbadyal/docker-py-revanced#557]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

Facebook

### Error log or link to the logs if using Github Action

```log
revanced-builder  | 2024-09-10 10:38:25.668 | INFO     | src.downloader.download:_download:35 - Trying to download facebook.zip from https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=7029582&key=d03d2c238735f3bd7d6bff098a08964bbfcc14ca&forcebaseapk=true
facebook.zip: 100%|██████████| 130M/130M [00:11<00:00, 11.4MiB/s]
revanced-builder  | 2024-09-10 10:38:38.314 | DEBUG    | src.downloader.download:_download:62 - Downloaded facebook.zip
revanced-builder  | Traceback (most recent call last):
revanced-builder  |   File "/app/main.py", line 63, in <module>
revanced-builder  |     main()
revanced-builder  |   File "/app/main.py", line 45, in main
revanced-builder  |     app.download_apk_for_patching(config)
revanced-builder  |   File "/app/src/app.py", line 74, in download_apk_for_patching
revanced-builder  |     self.download_file_name, self.download_dl = downloader.download(self.app_version, self)
revanced-builder  |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
revanced-builder  |   File "/app/src/downloader/download.py", line 130, in download
revanced-builder  |     return self.convert_to_apk(file_name), app_dl
revanced-builder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
revanced-builder  |   File "/app/src/downloader/download.py", line 92, in convert_to_apk
revanced-builder  |     subprocess.run(
revanced-builder  |   File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
revanced-builder  |     raise CalledProcessError(retcode, process.args,
revanced-builder  | subprocess.CalledProcessError: Command '['java', '-jar', 'apks/apkeditor-output.jar', 'm', '-i', 'apks/facebook.zip', '-o', 'apks/facebook.apk']' returned non-zero exit status 1.
revanced-builder exited with code 1
```

### ENVS

```Dotenv
PATCH_APPS=facebook
GLOBAL_CLI_DL=https://github.com/revanced/revanced-cli
GLOBAL_PATCHES_DL=https://github.com/revanced/revanced-patches
GLOBAL_PATCHES_JSON_DL=https://github.com/revanced/revanced-patches
GLOBAL_INTEGRATIONS_DL=https://github.com/revanced/revanced-integrations
GLOABAL_ARCHS_TO_BUILD=arm64-v8a
```

**Comment by nikhilbadyal** [comment]
Working fine for me. The APKMIRROR might not be having specified version when you tried to build.
<details>
<summary>Builder logs</summary>

2024-11-06 06:48:23.411 | DEBUG    | src.downloader.github:_get_release_assets:97 - Found APKEditor-1.4.1.jar to be downloaded from https://github.com/REAndroid/APKEditor/releases/download/V1.4.1/APKEditor-1.4.1.jar
2024-11-06 06:48:23.412 | INFO     | src.downloader.download:_download:35 - Trying to download apkeditor-output.jar from https://github.com/REAndroid/APKEditor/releases/download/V1.4.1/APKEditor-1.4.1.jar
apkeditor-output.jar: 100%|██████████████████████████████████████████████████████████████████████████████████████| 6.80M/6.80M [00:00<00:00, 17.5MiB/s]
2024-11-06 06:48:25.148 | DEBUG    | src.downloader.download:_download:62 - Downloaded apkeditor-output.jar
2024-11-06 06:48:25.736 | DEBUG    | src.utils:check_java:212 - Cool!! Java is available
2024-11-06 06:48:26.215 | INFO     | __main__:main:36 - Will Patch only ['facebook']
2024-11-06 06:48:26.215 | INFO     | __main__:main:38 - Trying to build facebook
2024-11-06 06:48:26.216 | INFO     | src.app:download_patch_resources:148 - Downloading resources for patching.
2024-11-06 06:48:26.489 | DEBUG    | src.downloader.github:_get_release_assets:97 - Found revanced-cli-4.6.0-all.jar to be downloaded from https://github.com/ReVanced/revanced-cli/releases/download/v4.6.0/revanced-cli-4.6.0-all.jar
2024-11-06 06:48:26.490 | INFO     | src.downloader.download:_download:35 - Trying to download d1dd3f8bdff4c4fbedc02f74dc4a853217af9769fcb559fe394d77806114dc55.jar from https://github.com/ReVanced/revanced-cli/releases/download/v4.6.0/revanced-cli-4.6.0-all.jar
2024-11-06 06:48:26.509 | DEBUG    | src.downloader.github:_get_release_assets:97 - Found revanced-patches-4.17.0.jar to be downloaded from https://github.com/ReVanced/revanced-patches/releases/download/v4.17.0/revanced-patches-4.17.0.jar
2024-11-06 06:48:26.511 | INFO     | src.downloader.download:_download:35 - Trying to download a6855d1ef1865aa30c7211449af31dbf2e7b309b06ad210f7a7a949cd91817cb.jar from https://github.com/ReVanced/revanced-patches/releases/download/v4.17.0/revanced-patches-4.17.0.jar
2024-11-06 06:48:26.510 | DEBUG    | src.downloader.github:_get_release_assets:97 - Found patches.json to be downloaded from https://github.com/ReVanced/revanced-patches/releases/download/v4.17.0/patches.json
2024-11-06 06:48:26.513 | INFO     | src.downloader.download:_download:35 - Trying to download 37749bcb77a6fef27498b7336f98bf71dc32ff129f774f6a9edc99911894f508.json from https://github.com/ReVanced/revanced-patches/releases/download/v4.17.0/patches.json
2024-11-06 06:48:26.517 | DEBUG    | src.downloader.github:_get_release_assets:97 - Found revanced-integrations-1.16.0.apk to be downloaded from https://github.com/ReVanced/revanced-integrations/releases/download/v1.16.0/revanced-integrations-1.16.0.apk
2024-11-06 06:48:26.518 | INFO     | src.downloader.download:_download:35 - Trying to download 6dee753a2b97e8d38c6f9a407df9fccdfb5263910503c914fb42560edd19e763.apk from https://github.com/ReVanced/revanced-integrations/releases/download/v1.16.0/revanced-integrations-1.16.0.apk
37749bcb77a6fef27498b7336f98bf71dc32ff129f774f6a9edc99911894f508.json: 100%|█████████████████████████████████████| 75.1k/75.1k [00:00<00:00, 1.24MiB/s]
2024-11-06 06:48:27.472 | DEBUG    | src.downloader.download:_download:62 - Downloaded 37749bcb77a6fef27498b7336f98bf71dc32ff129f774f6a9edc99911894f508.json
6dee753a2b97e8d38c6f9a407df9fccdfb5263910503c914fb42560edd19e763.apk: 100%|████████████████████████████████████████| 284k/284k [00:00<00:00, 1.94MiB/s]
2024-11-06 06:48:28.110 | DEBUG    | src.downloader.download:_download:62 - Downloaded 6dee753a2b97e8d38c6f9a407df9fccdfb5263910503c914fb42560edd19e763.apk3f8bdff4c4fbedc02f74dc4a853217af9769fcb559fe394d77806114dc55.jar:   0%|                                               | 0.00/48.5M [00:00<?, ?iB/s]
a6855d1ef1865aa30c7211449af31dbf2e7b309b06ad210f7a7a949cd91817cb.jar: 100%|██████████████████████████████████████| 3.12M/3.12M [00:00<00:00, 10.7MiB/s]
2024-11-06 06:48:28.237 | DEBUG    | src.downloader.download:_download:62 - Downloaded a6855d1ef1865aa30c7211449af31dbf2e7b309b06ad210f7a7a949cd91817cb.jar3f8bdff4c4fbedc02f74dc4a853217af9769fcb559fe394d77806114dc55.jar:  21%|███████▊                              | 10.0M/48.5M [00:00<00:00, 49.9MiB/s]
d1dd3f8bdff4c4fbedc02f74dc4a853217af9769fcb559fe394d77806114dc55.jar: 100%|██████████████████████████████████████| 48.5M/48.5M [00:01<00:00, 26.7MiB/s]
2024-11-06 06:48:29.901 | DEBUG    | src.downloader.download:_download:62 - Downloaded d1dd3f8bdff4c4fbedc02f74dc4a853217af9769fcb559fe394d77806114dc55.jar3f8bdff4c4fbedc02f74dc4a853217af9769fcb559fe394d77806114dc55.jar: 100%|██████████████████████████████████████| 48.5M/48.5M [00:01<00:00, 27.0MiB/s]
2024-11-06 06:48:30.010 | INFO     | src.app:download_apk_for_patching:64 - Downloading apk to be patched by scrapping
2024-11-06 06:48:34.370 | INFO     | src.downloader.apkmirror:specific_version:111 - Trying to guess facebook version.
2024-11-06 06:48:38.441 | INFO     | src.downloader.apkmirror:specific_version:115 - Guessed 488-0-0-78-79-456620372 for facebook
2024-11-06 06:48:38.444 | DEBUG    | src.downloader.apkmirror:extract_download_link:40 - Extracting download link from
https://www.apkmirror.com/apk/facebook-2/facebook/facebook-488-0-0-78-79-release/facebook-488-0-0-78-79-10-android-apk-download/
2024-11-06 06:48:42.940 | INFO     | src.downloader.download:_download:35 - Trying to download facebook.apk from https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=7538728&key=f26d317639a111ab9004a881875ccfabe7f9a9ec
facebook.apk: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 139M/139M [00:02<00:00, 49.6MiB/s]
2024-11-06 06:48:47.113 | DEBUG    | src.downloader.download:_download:62 - Downloaded facebook.apk
2024-11-06 06:48:47.114 | INFO     | __main__:main:47 - app_name: facebook, app_version: 488-0-0-78-79-456620372, experiment: False, cli_dl: https://github.com/revanced/revanced-cli/releases/latest, patches_dl: https://github.com/revanced/revanced-patches/releases/latest, integrations_dl: https://github.com/revanced/revanced-integrations/releases/latest, patches_json_dl: https://github.com/revanced/revanced-patches/releases/latest, exclude_request: [], include_request: [], resource: {'cli': {'file_name': 'd1dd3f8bdff4c4fbedc02f74dc4a853217af9769fcb559fe394d77806114dc55.jar', 'version': 'v4.6.0'}, 'integrations': {'file_name': '6dee753a2b97e8d38c6f9a407df9fccdfb5263910503c914fb42560edd19e763.apk', 'version': 'v1.16.0'}, 'patches': {'file_name': 'a6855d1ef1865aa30c7211449af31dbf2e7b309b06ad210f7a7a949cd91817cb.jar', 'version': 'v4.17.0'}, 'patches_json': {'file_name': '37749bcb77a6fef27498b7336f98bf71dc32ff129f774f6a9edc99911894f508.json', 'version': 'v4.17.0'}}, no_of_patches: 2, keystore_name: revanced.keystore, archs_to_build: [], options_file: options.json, download_file_name: facebook.apk, download_dl: https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=7538728&key=f26d317639a111ab9004a881875ccfabe7f9a9ec, download_source: https://www.apkmirror.com/apk/facebook-2/facebook/, package_name: com.facebook.katana, old_key: True, space_formatted: True
2024-11-06 06:48:48.010 | DEBUG    | src.parser:is_new_cli:149 - New cli
2024-11-06 06:48:48.010 | DEBUG    | src.parser:patch_app:211 - Sending request to revanced cli for building with args java ['-jar', PosixPath('apks/d1dd3f8bdff4c4fbedc02f74dc4a853217af9769fcb559fe394d77806114dc55.jar'), 'patch', PosixPath('apks/facebook.apk'), '-b', PosixPath('apks/a6855d1ef1865aa30c7211449af31dbf2e7b309b06ad210f7a7a949cd91817cb.jar'), '-m', PosixPath('apks/6dee753a2b97e8d38c6f9a407df9fccdfb5263910503c914fb42560edd19e763.apk'), '-o', PosixPath('apks/Re-facebook-488-0-0-78-79-456620372-2024NOV06_1218PM-output.apk'), '--keystore', PosixPath('apks/revanced.keystore'), '--options', PosixPath('apks/options.json'), '--keystore-entry-alias=alias', '--keystore-entry-password=ReVanced', '--keystore-password=ReVanced', '-i', 'Hide story ads', '-i', "Hide 'Sponsored Stories'"]
2024-11-06 06:48:48.736 | DEBUG    | src.parser:patch_app:218 - INFO: Loading patches 

2024-11-06 06:48:50.232 | DEBUG    | src.parser:patch_app:218 - INFO: Decoding app manifest 

2024-11-06 06:48:53.853 | DEBUG    | src.parser:patch_app:218 - INFO: Remove share targets excluded 

2024-11-06 06:48:53.857 | DEBUG    | src.parser:patch_app:218 - INFO: Hide mock location excluded 

2024-11-06 06:48:53.858 | DEBUG    | src.parser:patch_app:218 - INFO: Predictive back gesture excluded 

2024-11-06 06:48:53.858 | DEBUG    | src.parser:patch_app:218 - INFO: Export all activities excluded 

2024-11-06 06:48:53.858 | DEBUG    | src.parser:patch_app:218 - INFO: Remove screenshot restriction excluded 

2024-11-06 06:48:53.858 | DEBUG    | src.parser:patch_app:218 - INFO: Change data directory location excluded 

2024-11-06 06:48:53.858 | DEBUG    | src.parser:patch_app:218 - INFO: Spoof Wi-Fi connection excluded 

2024-11-06 06:48:53.858 | DEBUG    | src.parser:patch_app:218 - INFO: Spoof SIM country excluded 

2024-11-06 06:48:53.858 | DEBUG    | src.parser:patch_app:218 - INFO: Hex excluded 

2024-11-06 06:48:53.859 | DEBUG    | src.parser:patch_app:218 - INFO: Change version code excluded 

2024-11-06 06:48:53.859 | DEBUG    | src.parser:patch_app:218 - INFO: Spoof build info excluded 

2024-11-06 06:48:53.859 | DEBUG    | src.parser:patch_app:218 - INFO: Change package name excluded 

2024-11-06 06:48:53.859 | DEBUG    | src.parser:patch_app:218 - INFO: Enable Android debugging excluded 

2024-11-06 06:48:53.859 | DEBUG    | src.parser:patch_app:218 - INFO: Override certificate pinning excluded 

2024-11-06 06:48:53.859 | DEBUG    | src.parser:patch_app:218 - INFO: Remove screen capture restriction excluded 

2024-11-06 06:48:53.859 | DEBUG    | src.parser:patch_app:218 - INFO: Setting patch options 

2024-11-06 06:48:59.488 | DEBUG    | src.parser:patch_app:218 - INFO: Executing patches 

SEVERE: Hide 'Sponsored Stories' failed:
app.revanced.patcher.patch.PatchException: Failed to resolve GetSponsoredDataModelTemplateFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:30)
        at app.revanced.util.BytecodeUtilsKt.resultOrThrow(BytecodeUtils.kt:22)
        at app.revanced.patches.facebook.ads.mainfeed.HideSponsoredStoriesPatch.execute(HideSponsoredStoriesPatch.kt:34)
        at app.revanced.patches.facebook.ads.mainfeed.HideSponsoredStoriesPatch.execute(HideSponsoredStoriesPatch.kt:22)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:173)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:303)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:302)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
 
2024-11-06 06:49:01.284 | DEBUG    | src.parser:patch_app:218 - INFO: Hide story ads succeeded 

2024-11-06 06:49:01.308 | DEBUG    | src.parser:patch_app:218 - INFO: Compiling patched dex files 

2024-11-06 06:49:08.705 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes.dex 

2024-11-06 06:49:09.271 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes2.dex 

2024-11-06 06:49:20.005 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes3.dex 

2024-11-06 06:49:20.738 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes4.dex 

2024-11-06 06:49:26.544 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes5.dex 

2024-11-06 06:49:26.904 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes6.dex 

2024-11-06 06:49:32.975 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes7.dex 

2024-11-06 06:49:33.088 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes8.dex 

2024-11-06 06:49:37.643 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes9.dex 

2024-11-06 06:49:37.931 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes10.dex 

2024-11-06 06:49:41.990 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes11.dex 

2024-11-06 06:49:42.667 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes12.dex 

2024-11-06 06:49:45.983 | DEBUG    | src.parser:patch_app:218 - INFO: Compiled classes13.dex 

2024-11-06 06:49:54.666 | DEBUG    | src.parser:patch_app:218 - INFO: Aligning APK 

2024-11-06 06:49:55.947 | DEBUG    | src.parser:patch_app:218 - INFO: Signing APK 

2024-11-06 06:49:59.647 | DEBUG    | src.parser:patch_app:218 - INFO: Saved to /workspaces/docker-py-revanced/apks/Re-facebook-488-0-0-78-79-456620372-2024NOV06_1218PM-output.apk 

2024-11-06 06:49:59.746 | INFO     | src.parser:patch_app:220 - Patching completed for app app_name: facebook, app_version: 488-0-0-78-79-456620372, experiment: False, cli_dl: https://github.com/revanced/revanced-cli/releases/latest, patches_dl: https://github.com/revanced/revanced-patches/releases/latest, integrations_dl: https://github.com/revanced/revanced-integrations/releases/latest, patches_json_dl: https://github.com/revanced/revanced-patches/releases/latest, exclude_request: [], include_request: [], resource: {'cli': {'file_name': 'd1dd3f8bdff4c4fbedc02f74dc4a853217af9769fcb559fe394d77806114dc55.jar', 'version': 'v4.6.0'}, 'integrations': {'file_name': '6dee753a2b97e8d38c6f9a407df9fccdfb5263910503c914fb42560edd19e763.apk', 'version': 'v1.16.0'}, 'patches': {'file_name': 'a6855d1ef1865aa30c7211449af31dbf2e7b309b06ad210f7a7a949cd91817cb.jar', 'version': 'v4.17.0'}, 'patches_json': {'file_name': '37749bcb77a6fef27498b7336f98bf71dc32ff129f774f6a9edc99911894f508.json', 'version': 'v4.17.0'}}, no_of_patches: 2, keystore_name: revanced.keystore, archs_to_build: [], options_file: options.json, download_file_name: facebook.apk, download_dl: https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=7538728&key=f26d317639a111ab9004a881875ccfabe7f9a9ec, download_source: https://www.apkmirror.com/apk/facebook-2/facebook/, package_name: com.facebook.katana, old_key: True, space_formatted: True in 71.74 seconds.

</details>
